### ISSUE TITLE
Transition to workbench

### ISSUE THREAD

**Issue by csoneson** [carpentries-incubator/bioc-rnaseq#15]
Hi @zkamvar,

similarly to https://github.com/carpentries-incubator/bioc-intro/issues/76 and https://github.com/carpentries-incubator/bioc-project/issues/48, I would like to ask for your help with transitioning also this repository to the new workbench format. 

Thanks a lot in advance, and let me know if I can do anything to help!

All the best,
Charlotte

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

**Comment by zkamvar** [comment]
I'll add it to the list!

**Comment by csoneson** [comment]
Hi @zkamvar - thanks for your recent updates concerning the Workbench transition. I followed the discussion over at the [bioc-intro](https://github.com/carpentries-incubator/bioc-intro/issues/76) lesson, and I just wanted to let you know that similar to what Laurent did there, I also pulled down and tested https://github.com/fishtree-attempt/bioc-rnaseq/ locally, and everything seems to be running smoothly - the output also looks nice 🙂. Please let me know if there's anything else I can do to help in the transition. Thanks!

**Comment by zkamvar** [comment]
Thank you! I should be getting to the transition today. I was cleaning up a few things yesterday to make the transition a bit smoother (e.g. transforming raw github links to relative paths that will resolve correctly: https://github.com/carpentries/lesson-transition/blob/0478e2f8393bad6ceba70e0de6328d2c6d4f2ba2/carpentries-incubator/bioc-rnaseq.R#L21-L26).

I am going to send a message here notifying everyone on this repository about what to expect and then set all permissions to read except for @csoneson, so that they can give permissions. 


Here are some resources in the meantime:

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
1. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
1. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

**Comment by zkamvar** [comment]
This lesson will be converted to use [The Carpentries Workbench][workbench]
To prevent accidental reversion of the changes, we are temporarily revoking
write access for all collaborators on this lesson:

 - [ ] @lgatto (maintain)
 - [ ] @rcastelo (maintain)
 - [ ] @csoneson (admin)
 - [ ] @jdrnevich (maintain)

If you no longer wish to have write access to this repository, you do not
need to do anything further.

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
2. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
3. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

If you wish to regain write access, please re-clone the repository on your machine and
then comment here with `I am ready for write access :rocket:` and the
admin maintainer of this repository will restore your permissions.

If you have any questions, please reply here and tag @zkamvar

[workbench]: https://carpentries.github.io/workbench

**Comment by zkamvar** [comment]
The deed is done. @csoneson, the infrastructure takes [a few minutes to bootstrap and cache the packages for the lesson build](https://github.com/carpentries-incubator/bioc-rnaseq/actions/runs/4208173685/jobs/7303886970)). Once the build is done, I will switch github pages to deploy from the `gh-pages` branch and you will have your workbench lesson. 

Thank you all for your enthusiasm and your patience!

**Comment by zkamvar** [comment]
Note: this is taking a bit longer than usual because there was a 404 error in the package cache setup, so I had to restart the job. I suspect it was ephemeral, but I will keep you posted.

**Comment by zkamvar** [comment]
It turns out that the 404 error comes from [step 6, line 3758 of the run](https://github.com/carpentries-incubator/bioc-rnaseq/actions/runs/4208173685/jobs/7304140799#step:6:3758):


```
  Warning message:
  curl: (22) The requested URL returned error: 404 
  Error: 
  ! in callr subprocess.
  Caused by error: 
  ! failed to find source for 'data.table 1.14.8' in package repositories
```

Considering that data.table was _just_ released today (less than 12 hours ago: `Date/Publication: 2023-02-17 12:20:12 UTC`), It is fair to say that this is indeed an ephemeral issue (it could be that it had not yet been propagated to all the mirrors yet) as the build for the beta test worked well: https://fishtree-attempt.github.io/bioc-rnaseq/

I will be travelling over the weekend, but I would suggest to let this wait a day or so and then re-start the build. By then the mirrors should have updated and you will not see the problem.

**Comment by csoneson** [comment]
Thanks @zkamvar, this is great! I just checked in at PPM and it seems that `data.table` 1.14.8 is available since 10 minutes or so 🙂 I'll try to kick off the CI again and see if it resolves it.

**Comment by csoneson** [comment]
Seems to have worked 🎉

**Comment by zkamvar** [comment]
wunderbar!

The Workbench version is now live: https://carpentries-incubator.github.io/bioc-rnaseq/

In addition, here is [map of commits that were changed during the transition](https://github.com/carpentries/lesson-transition/blob/main/release/carpentries-incubator/bioc-rnaseq-commit-map.hash)
